### ISSUE TITLE
📚 Medium: スキーマ駆動文書化システムの導入

### ISSUE THREAD

**Issue by YunosukeYoshino** [YunosukeYoshino/Suno-Maker#39]
## 問題概要

現在のプロジェクトにはRyukyuInteractiveスタイルのスキーマ駆動文書化システムが不足しており、ドメイン知識の体系的管理とチーム間の知識共有に課題がある。

## 現状の課題

1. **ドメイン知識の散在**: エンティティの仕様がコードに埋もれている
2. **ビジネスルール不明確**: 暗黙的なルールが多数存在
3. **新規参加者の学習コスト**: オンボーディング時の情報収集困難
4. **仕様変更時の影響範囲**: 関連文書の更新漏れリスク

#### `docs/domain/entities/prompt-entity.md`
```yaml
---
icon: 🎵
schema:
  name:
    type: string
    required: true
    description: エンティティ名
  purpose:
    type: string
    required: true
    description: ビジネス上の目的
  business_rules:
    type: multi-text
    required: true
    description: ビジネスルール一覧
  properties:
    type: multi-text
    description: 主要プロパティ
  validation_rules:
    type: multi-text
    description: 検証ルール
  usage_examples:
    type: multi-text
    description: 使用例
---

# Prompt Entity

## Purpose
AI音楽生成のためのプロンプト管理エンティティ

## Business Rules
- titleは1文字以上100文字以内必須
- GenreとLanguageは必須設定
- 生成統計の自動更新機能
- 品質スコアの自動計算

## Properties
- id: 一意識別子（UUID）
- title: プロンプトタイトル
- genre: 音楽ジャンル（Genre値オブジェクト）
- language: 言語設定（Language値オブジェクト）
- styleField: スタイル設定（StyleField値オブジェクト）

## Validation Rules
- Zodスキーマによる実行時検証
- カスタム値オブジェクト検証
- 言語とジャンルの組み合わせ妥当性チェック

## Usage Examples
- プロンプト作成ページでの新規作成
- テンプレートライブラリでの管理
- 最適化機能での品質向上
```

#### `docs/domain/value-objects/genre.md`
```yaml
---
icon: 🎶
schema:
  name: string
  valid_values: multi-text
  business_purpose: string
  validation_rules: multi-text
---

# Genre Value Object

## Valid Values
- Pop, Rock, Jazz, Classical
- J-Pop, J-Rock（日本語用推奨）
- Electronic, Hip-Hop, Country

## Business Purpose
音楽ジャンルの型安全な表現と検証

## Validation Rules
- 事前定義済み値のみ許可
- 文字列の大文字小文字区別
- 配列・単一値の両方サポート
```

#### `docs/business-rules/index.md`
```yaml
---
icon: 📋
schema:
  category: string
  rules: multi-text
  enforcement: string
---

# Business Rules Index

## Prompt Creation Rules
- 必須フィールド検証
- 文字数制限の適用
- ジャンル・言語適合性チェック

## Quality Assessment Rules
- 品質スコア計算ロジック
- 最適化推奨基準
- 成功率統計の更新タイミング
```

#### `.claude/project-knowledge.md`
```markdown
# Project Knowledge Base

## Domain Patterns
- エンティティ不変性パターン
- 値オブジェクト設計原則
- ユースケース実装テンプレート

## Common Issues & Solutions
- レイヤー境界違反 → 型定義の適切配置
- UUID生成不整合 → generateUUID()統一
- テスト環境エラー → 型定義整備
```

### Phase 1: 基盤構築（3日）
- [ ] `docs/domain/` ディレクトリ構造作成
- [ ] エンティティ文書テンプレート作成
- [ ] Promptエンティティ文書完成

### Phase 2: 全体展開（5日）
- [ ] 全エンティティ文書化（Lyrics, Song, Template, SuccessExample）
- [ ] 値オブジェクト文書化
- [ ] ビジネスルール体系化

### Phase 3: 知見統合（2日）
- [ ] `.claude/project-knowledge.md` 整備
- [ ] CLAUDE.md更新（文書化ルール追記）
- [ ] 文書間のリンク整備

## 受け入れ基準

- [ ] 全ドメインエンティティの構造化文書完成
- [ ] frontmatterスキーマの一貫性確保
- [ ] ビジネスルールの機械可読化
- [ ] 新規参加者向けナビゲーション整備
- [ ] 既存テストの全通過維持

## 期待効果

1. **知識共有効率化**: チーム間の仕様理解統一
2. **オンボーディング高速化**: 新規参加者の学習コスト削減
3. **仕様変更影響分析**: 関連箇所の特定容易化
4. **品質向上**: ビジネスルールの明文化による実装精度向上

## 優先度

**Medium** - 中長期的なチーム効率向上に貢献、戦略的投資価値高

## 関連

- RyukyuInteractive「スキーマ駆動文書化」ルール適用
- プロジェクト知識の体系的管理基盤構築
- Issue #36-38の基盤改善と合わせた総合的改善
